name: build_osx

on:
  # Enable manual run from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-10.15

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build-commands
        run: |
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          uname -a
          cd $GITHUB_WORKSPACE
          ls -lh
          cd src
          CXX=g++-11 make
      - name: Check linking
        run: |
          echo "Checking for dylib linking"
          otool -L $GITHUB_WORKSPACE/src/Darwin/muscle
      - name: Check execution
        run: |
          chmod +x $GITHUB_WORKSPACE/src/Darwin/muscle
          $GITHUB_WORKSPACE/src/Darwin/muscle -h
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: muscle-osx-binary
          path: src/Darwin/muscle
